### ISSUE TITLE
How to run server...

### ISSUE THREAD

**Issue by SledgehammerPL** [Pushjet/Pushjet-Server-Api#23]
I'm trying to run server, but ngninx log says:

*1 connect() to unix:/var/run/gunicorn/pushjet-api.sock failed (111: Connection refused) while connecting to upstream,

and gunicorn's log says:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 365, in import_app
    __import__(module)
ImportError: No module named wsgi

**Comment by hugoShaka** [comment]
The `wsgi.py` is in the `.gitignore`, could you stage it for commit just once ? Is the WSGI file different from the django one ?

**Comment by SledgehammerPL** [comment]
Found solution ; gunicorn conf - the difference is last line: 'wsgi' -> 'application:app'

CONFIG = {
    'mode': 'wsgi',
    'working_dir': '/usr/src/Pushjet-Server-Api/',
    'python': '/usr/bin/python2',
    'args': (
        '--bind=unix:/var/run/gunicorn/pushjet-api.sock',
        '--workers=2',
        '--timeout=30',
        'application:app',
    ),
}

**Comment by ghost** [comment]
I'm having this same issue, and changing that line to `application:app` doesn't seem to fix it. Is that what it's supposed to be? It's strange, I'm not seeing any more errors in the gunicorn log, but it's clearly not starting. If I start it manually, it complains about there not being a module named wsgi.
